"""Fix user I

Revision ID: 079218219df6
Revises: 38b83271db50
Create Date: 2025-02-05 04:10:37.153889

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '079218219df6'
down_revision: Union[str, None] = '38b83271db50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'username',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###
