"""google_id

Revision ID: f06e6de7a5ab
Revises: 36f9086a73e5
Create Date: 2025-03-07 02:14:22.138298

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f06e6de7a5ab'
down_revision: Union[str, None] = '36f9086a73e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('google_id', sa.Text(), nullable=True))
    op.alter_column('User', 'username',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=True)
    op.alter_column('User', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.create_unique_constraint(None, 'User', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'hashed_password',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('User', 'username',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=False)
    op.drop_column('User', 'google_id')
    # ### end Alembic commands ###
