"""initial

Revision ID: 5a84b4016794
Revises: e1ff82e3ec69
Create Date: 2025-02-05 18:42:20.511112

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a84b4016794'
down_revision: Union[str, None] = 'e1ff82e3ec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
