"""yandex_id

Revision ID: 64a67bba72ca
Revises: f06e6de7a5ab
Create Date: 2025-03-10 16:55:31.286117

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64a67bba72ca'
down_revision: Union[str, None] = 'f06e6de7a5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('yandex_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'User', ['yandex_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'yandex_id')
    # ### end Alembic commands ###
