"""Initial migration

Revision ID: 7efafc2f51e2
Revises: 
Create Date: 2025-02-05 02:44:39.905584

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7efafc2f51e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'username',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.alter_column('User', 'hashed_password',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.alter_column('User', 'hashed_password',
                    existing_type=sa.String(length=255),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    op.alter_column('User', 'username',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(),
                    existing_nullable=False)
    # ### end Alembic commands ###
