"""avatar_paths

Revision ID: d700b1611f5c
Revises: 64a67bba72ca
Create Date: 2025-03-11 05:21:03.056336

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd700b1611f5c'
down_revision: Union[str, None] = '64a67bba72ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('google_avatar_path', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('yandex_avatar_path', sa.Text(), nullable=True))
    op.drop_constraint('User_avatar_path_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_avatar_path_key', 'User', ['avatar_path'])
    op.drop_column('User', 'yandex_avatar_path')
    op.drop_column('User', 'google_avatar_path')
    # ### end Alembic commands ###
